// Generates a DRAFT AfCFTA Certificate of Origin PDF from a business profile.
//
// IMPORTANT: this is a draft-generation tool, not an official customs
// document. Real Certificates of Origin must ultimately be issued/stamped by
// an authorized body (e.g. a chamber of commerce or customs authority) in
// most AfCFTA member states. PassKonnect's job is to remove 90% of the
// friction of getting to that point — pre-filling the paperwork correctly —
// not to replace the official issuing authority. This disclaimer is
// intentionally printed on every generated certificate.

import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const OUTPUT_DIR = path.resolve("generated", "certificates");

function humanize(slug) {
  return slug ? slug.replaceAll("_", " ") : slug;
}

export function ensureOutputDir() {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

export function certificatePdfPath(certificateId) {
  return path.join(OUTPUT_DIR, `${certificateId}.pdf`);
}

export function generateCertificatePdf({ certificateId, business, destinationCountry }) {
  ensureOutputDir();
  const filePath = certificatePdfPath(certificateId);
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // Header
  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .text("AfCFTA Certificate of Origin — DRAFT", { align: "center" });
  doc.moveDown(0.3);
  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#555555")
    .text("Generated by PassKonnect — not an official customs document until countersigned by an authorized issuing body.", {
      align: "center",
    });
  doc.fillColor("#000000");
  doc.moveDown(1.5);

  const row = (label, value) => {
    doc.font("Helvetica-Bold").fontSize(11).text(label, { continued: true });
    doc.font("Helvetica").text(`  ${value || "—"}`);
    doc.moveDown(0.4);
  };

  doc.font("Helvetica-Bold").fontSize(13).text("Exporter Details");
  doc.moveDown(0.3);
  row("Business Name:", business.name);
  row("Country of Origin:", business.country);
  row("Business Registration No.:", business.registrationNumber);
  row("Contact Email:", business.contactEmail);
  row("Contact Phone:", business.contactPhone);

  doc.moveDown(0.8);
  doc.font("Helvetica-Bold").fontSize(13).text("Goods Details");
  doc.moveDown(0.3);
  row("Product Category:", humanize(business.productCategory));
  row("Product Description:", business.productDescription);
  row("Origin of Inputs/Materials:", business.inputsOrigin);

  doc.moveDown(0.8);
  doc.font("Helvetica-Bold").fontSize(13).text("Shipment");
  doc.moveDown(0.3);
  row("Destination Country:", destinationCountry);
  row("Date Generated:", new Date().toISOString().slice(0, 10));
  row("Certificate ID:", certificateId);

  doc.moveDown(1.2);
  doc
    .fontSize(9)
    .fillColor("#555555")
    .text(
      "This draft is generated from information supplied by the exporter and has not been independently verified. " +
        "It must be reviewed and countersigned by an authorized issuing body (e.g. a national chamber of commerce or " +
        "customs authority) before it can be used to claim AfCFTA preferential tariff treatment.",
      { align: "left" }
    );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
  });
}
