// Generates a DRAFT AfCFTA Certificate of Origin PDF from a business profile.
//
// IMPORTANT: this is a draft-generation tool, not an official customs
// document. Real Certificates of Origin must ultimately be issued/stamped by
// an authorized body (e.g. a chamber of commerce or customs authority) in
// most AfCFTA member states. PassKonnect's job is to remove 90% of the
// friction of getting to that point — pre-filling the paperwork correctly —
// not to replace the official issuing authority. This disclaimer is
// intentionally printed on every generated certificate.

import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { putBlob } from "./lib/blobStorage.js";

function humanize(slug) {
  return slug ? slug.replaceAll("_", " ") : slug;
}

function humanizeVerification(status) {
  if (status === "verified") return "Verified by PassKonnect";
  if (status === "pending") return "Verification in progress";
  return "Not yet verified";
}

export function certificateBlobKey(certificateId) {
  return `certificates/${certificateId}.pdf`;
}

export async function generateCertificatePdf({ certificateId, business, destinationCountry }) {
  const key = certificateBlobKey(certificateId);

  const frontendUrl = process.env.FRONTEND_URL || "http://localhost:5173";
  const profileUrl = `${frontendUrl}/p/${business.id}`;
  const qrDataUrl = await QRCode.toDataURL(profileUrl, { margin: 1, width: 160 });

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  // Header
  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .text("AfCFTA Certificate of Origin — DRAFT", { align: "center" });
  doc.moveDown(0.3);
  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#555555")
    .text("Generated by PassKonnect — not an official customs document until countersigned by an authorized issuing body.", {
      align: "center",
    });
  doc.fillColor("#000000");
  doc.moveDown(1.5);

  const row = (label, value) => {
    doc.font("Helvetica-Bold").fontSize(11).text(label, { continued: true });
    doc.font("Helvetica").text(`  ${value || "—"}`);
    doc.moveDown(0.4);
  };

  doc.font("Helvetica-Bold").fontSize(13).text("Exporter Details");
  doc.moveDown(0.3);
  row("Business Name:", business.name);
  row("Country of Origin:", business.country);
  row("Business Registration No.:", business.registrationNumber);
  row("Contact Email:", business.contactEmail);
  row("Contact Phone:", business.contactPhone);

  doc.moveDown(0.8);
  doc.font("Helvetica-Bold").fontSize(13).text("Goods Details");
  doc.moveDown(0.3);
  row("Product Category:", humanize(business.productCategory));
  row("Product Description:", business.productDescription);
  row("Origin of Inputs/Materials:", business.inputsOrigin);

  doc.moveDown(0.8);
  doc.font("Helvetica-Bold").fontSize(13).text("Shipment");
  doc.moveDown(0.3);
  row("Destination Country:", destinationCountry);
  row("Date Generated:", new Date().toISOString().slice(0, 10));
  row("Certificate ID:", certificateId);

  doc.moveDown(1.2);
  doc
    .fontSize(9)
    .fillColor("#555555")
    .text(
      "This draft is generated from information supplied by the exporter and has not been independently verified. " +
        "It must be reviewed and countersigned by an authorized issuing body (e.g. a national chamber of commerce or " +
        "customs authority) before it can be used to claim AfCFTA preferential tariff treatment.",
      { align: "left" }
    );
  doc.fillColor("#000000");

  // QR code linking to the business's public, QR-verified profile page.
  doc.moveDown(1.2);
  const qrSize = 80;
  const qrX = doc.page.margins.left;
  const qrY = doc.y;
  doc.image(qrDataUrl, qrX, qrY, { width: qrSize, height: qrSize });
  doc
    .fontSize(9)
    .font("Helvetica-Bold")
    .text(humanizeVerification(business.verificationStatus), qrX + qrSize + 12, qrY + 22, { width: 260 });
  doc
    .fontSize(8)
    .font("Helvetica")
    .fillColor("#555555")
    .text("Scan to view this business's verified PassKonnect profile.", qrX + qrSize + 12, qrY + 40, { width: 260 });
  doc.fillColor("#000000");

  doc.end();

  const buffer = await new Promise((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  await putBlob(key, buffer, "application/pdf");
  return key;
}
